// src/components/Prose/index.tsx
/** @jsxImportSource react */

const Prose = ({ children }: { children: React.ReactNode }) => (
  <div
    className="prose mx-auto h-[80vh] max-h-[80vh] w-full max-w-[unset] overflow-auto
  prose-a:no-underline
  prose-blockquote:border-lilac prose-blockquote:bg-light-lilac prose-blockquote:py-1 prose-blockquote:not-italic
  prose-strong:tracking-wider
  prose-code:text-[unset]
  prose-pre:bg-code-editor-one-dark-pro prose-pre:text-base prose-pre:font-bold
  prose-img:m-0
  "
  >
    {children}
  </div>
);

export default Prose;

// src/components/Prose/qwik-prose.tsx
import { component$ } from "@builder.io/qwik";

export default component$(({ innerHTML }: { innerHTML: string }) => {
  return (
    <section
      // SHOULD add a background
      id="sectionProse"
      class="prose mx-auto w-full bg-background-light-gray px-4 py-6 text-base prose-a:decoration-wavy
    prose-a:underline-offset-4 prose-blockquote:pr-[1em]
    prose-strong:tracking-wider
    prose-code:text-[unset]
    prose-pre:bg-code-editor-one-dark-pro
    prose-pre:text-base prose-pre:font-bold prose-img:m-0
    dark:bg-primary-dark-gray
    dark:text-background-light-gray
    md:px-10 md:py-12 lg:text-lg"
      dangerouslySetInnerHTML={innerHTML}
    ></section>
  );
});
